routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['auth', 'check.logout', 'set.locale'])->group(function () {
    Route::resource('posts', PostController::class)->except([
        'edit',
        'update',
        'destroy'
    ]);

    Route::resource('posts.comments', CommentController::class)->only([
        'index',
        'store'
    ])->shallow();

    Route::resource('posts.likes', LikeController::class)->only([
        'index',
        'store',
        'destroy'
    ])->shallow();

    Route::get('/language', [LanguageController::class, 'change'])->name('change-language');
});

Route::get('/login', [LoginController::class, 'getLogin'])->name('login');
Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $table = 'posts';
    protected $fillable = [
        'title',
        'content',
        'like',
        'image',
        'public_date',
        'status'
    ];

    public function comments()
    {
       return $this->hasMany(Comment::class, 'post_id', 'id');
    }

    public function likes()
    {
        return $this->hasMany(Like::class, 'post_id', 'id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Post\CreatePostRequest;
use App\Services\PostService;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    protected $postService;

    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->postService->getPostsByStatus(config('constants.status.publish'));
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $this->postService->create($request);
        return redirect()->route('posts.index')->with('message', 'create success');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = $this->postService->find($id);
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@push('css')
    <link rel="stylesheet" href="{{ asset('css/product.css') }}">
@endpush
@section('content')
    <div class="container mb-4">
        <h1 class="text-center mt-5">{{ trans('label.create_post') }}</h1>
        <div class="btn-back-index mt-3 mb-3">
            <a href="{{ route('posts.index') }}">
                <i class="fas fa-backward" ></i>
                {{ trans('label.back') }}
            </a>
        </div>
        <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">{{ trans('label.title') }}</label>
                <input type="text" class="form-control" id="title" placeholder="Enter title" name="title">
                @error('title')
                <small class="form-text text-muted" style="color: red !important;">{{ $message }}</small>
                @enderror
            </div>
            <div class="form-group">
                <label for="content">{{ trans('label.content') }}</label>
                <input type="text" class="form-control" id="content" placeholder="Enter content" name="content">
                @error('content')
                <small class="form-text text-muted" style="color: red !important;">{{ $message }}</small>
                @enderror
            </div>
            <div class="form-group">
                <div class="wrapper-image">
                    <label>{{ trans('label.image') }}</label>
                    <div class="box-image">
                        <img src="{{ asset('images/default-image.jpg') }}" alt="" width="150px" height="150px" id="preview-image">
                    </div>
                    <div class="btn btn-sm btn-success btn-image">
                        {{ trans('label.choose_image') }} <i class="fas fa-upload"></i>
                        <input type="file" id="file-image" name="image">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label style="display: block">{{ trans('label.public_date') }}</label>
                <input type="datetime-local" name="public_date">
            </div>
            <button type="submit" class="btn btn-primary">{{ trans('label.create') }}</button>
        </form>
    </div>
@endsection
@push('script')
    <script src="{{ asset('js/post.js') }}"></script>
@endpush

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if(\Session::has('message'))
            <div class="mt-4">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ \Session::get('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endif
        <h1 class="text-center mt-5">{{ trans('label.list_post') }}</h1>
        <div class="btn-add-post text-right mt-4 mb-4">
            <a href="{{ route('posts.create') }}" class="btn btn-sm btn-primary">{{ trans('label.add_post') }}</a>
        </div>
        <div class="row">
            @foreach($posts as $post)
                <div class="col-xl-3">
                    <div class="card" style="width: 100%">
                        <img class="card-img-top"
                             src="{{ asset('storage/images/uploads/'.\App\Helpers\Helper::checkImageNull($post->image)) }}"
                             alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ $post->title }}</h5>
                            <p class="card-text">{{ $post->content }}</p>
                            <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary btn-sm">{{ trans('label.view_detail') }}</a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@push('script')

@endpush

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div class="mt-4 mb-4">
            <a href="{{ route('posts.index') }}">back</a>
        </div>
        <div class="card" >
            <img class="card-img-top" src="{{ asset('storage/images/uploads/'.\App\Helpers\Helper::checkImageNull($post->image)) }}" alt="Card image cap" >
            <div class="card-body">
                <h5 class="card-title">{{ $post->title }}</h5>
                <p class="card-text">{{ $post->content }}</p>
                <p id="count-comments"></p>
                <p id="count-likes">
                    <i class="far fa-thumbs-up"></i> <span></span>
                </p>
                <div class="d-flex flex-row">
                    <span style="cursor:pointer; margin-right: 10px" id="btn-comment-now">
                        <i class="far fa-comments"></i> comment now
                    </span>
                    <span style="cursor:pointer; margin-right: 10px" id="btn-like" username="{{ auth()->user()->name }}" status="0">
                        <i class="far fa-thumbs-up"></i> like
                    </span>
                </div>
            </div>
        </div>

        <div class="card mt-2">
            <div class="card-body">
                <h5 class="card-title">All comments</h5>
                <div id="list-comments"></div>
                <div style="margin: 20px 0px; height: 1px; background: black"></div>
                <form id="form-comment">
                    <div class="form-group" style="display: flex">
                        <input type="text" class="form-control" id="content" placeholder="Enter your comment" name="content" autocomplete="off">
                        <button class="btn btn-primary">send</button>
                    </div>
                    <small class="form-text text-muted" style="color: red !important;" id="error-content"></small>
                </form>
            </div>
        </div>
    </div>

    {{--route--}}
    <input type="hidden" id="route-get-list-comments" data-url="{{ route('posts.comments.index', $post->id) }}">
    <input type="hidden" id="route-store-comment" data-url="{{ route('posts.comments.store', $post->id) }}">
    <input type="hidden" id="route-get-list-likes" data-url="{{ route('posts.likes.index', $post->id) }}">
    <input type="hidden" id="route-store-like" data-url="{{ route('posts.likes.store', $post->id) }}">
    <input type="hidden" id="route-destroy-like" data-url="{{ url('/likes') }}">
@endsection

@push('script')
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="{{ asset('js/comment.js') }}"></script>
@endpush